### ISSUE TITLE
checking neighboring boxes

### ISSUE THREAD

**Issue by penguyen1** [penguyen1/click_click_BOOM#1]
**What I'm trying to solve:**
In click_click_BOOM (minesweeper), when you click on a box, it should ideally check all the boxes around it. On a 5x5 board (numbered 1-25), I need to figure out an algorithm or way to differentiate box #5 from #6, #10 from #11, and etc. Box #5 is located on the right edge of the board whereas box #6 will be displayed on the left edge of the board. If I were to click on Box #5, I should ideally only check boxes 4, 9 and 10, and NOT box #6 because it is located across the board. 

```
                  1   2   3   4   5     <--- if I click box #5, I should only check box #4, #9 and #10
                  6   7   8   9   10                   
                  11  12  13  14  15
                  16  17  18  19  20
                  21  22  23  24  25
```

**What I've tried so far:**
As a solution, I've created 3 algorithms to resolve this issue:
       1. An algorithm for boxes on the right-edge - if ( boxValue % 5 === 0)
           - [-6, -5, -1, 4, 5] will only check the topLeft, above, left, bottomLeft and below boxes only
       2. An algorithm for boxes on the left-edge - if (boxValue % 5 === 1)
            - [-5, -4, 1, 5, 6] will only check the above, topRight, right, bottomRight and below boxes only
       3. An algorithm for all other boxes 
            - [-6, -5, -4, -1, 1, 4, 5, 6] will check the topLeft, above, topRight, left, right, bottomLeft, below and bottomRight boxes

**My Problem:**
The problem is that I do not know fully how to implement this idea/method to the usage of storing each box location as a binary string. Storing each box isn't the problem, but figuring out the neighboring boxes of a particular box is. Thus, I found that assigning each box to an integer value would work best.

**My question is:** 
- Would this algorithm/method be ok with finding the neighboring boxes? 
- The usage of binary strings sounds interesting, but I'm afraid that I will spend a lot of time trying to grasp the concepts and waste valuable project time in making my game.

**Comment by jasonseminara** [comment]
is this still an issue? Would you like to meet about this?

**Comment by penguyen1** [comment]
no, this function works perfectly (knock on wood). i'm just leaving this issue open in case i might need to modify it again in the future

**Comment by jasonseminara** [comment]
I retract my original idea of the single, wrapping long number. A 2D array ( board[ i ][ j ]) would probably make the most sense, but if you have it working, stay the course.
